spring:
  profiles:
    active: development
server:
  port: 0
---
spring:
  profiles: development
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
---
spring:
  profiles: docker
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka
#    registryFetchIntervalSeconds: 5
#  instance:
#    hostname: ${DOCKER_IP:192.168.99.100}
#    instance-id: ${spring.application.name}:${random.int}
#    leaseRenewalIntervalInSeconds: 5
---
spring:
  profiles: test
eureka:
  client:
    enabled: false
---
spring:
  profiles: cloud
#eureka:
#  instance:
#    hostname: ${vcap.application.uris[0]:localhost}
#    nonSecurePort: 80
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#    leaseRenewalIntervalInSeconds: 5
#  client:
#    region: default
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/
