apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: order-web
  name: order-web
 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: order-web
  
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: order-web
    spec:
      containers:
      - name: order-web
        image: order-web:latest
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8888 # The port that the container exposes
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
---
apiVersion: v1
kind: Service
metadata:
  
  labels:
    app: order-web
  name: order-web
  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: order-web
  type: ClusterIP
